INSERT INTO `categories` (`name`, `description`) VALUES
    ('Mod of the year', ''),
    ('Best Yunii fanart', ''),
    ('Artist of the year', ''),
    ('Most chaotic pestie', ''),
    ('Sussiest pestie', ''),
    ('Most gassy pestie', ''),
    ('Most biteable pestie', ''),
    ('The chaddest pestie', ''),
    ('Most gamba addicted pestie', ''),
    ('Best gambler', ''),
    ('Worst gambler', ''),
    ('Best gamer', ''),
    ('Most helpful pestie', ''),
    ('Most wholesome pestie', ''),
    ('Most nice pestie', ''),
    ('Best discord streamer', ''),
    ('Best discord chatter', ''),
    ('Most banned pestie', '');
