INSERT INTO `categories` (`name`, `description`) VALUES
    ('Mod of the year', ''),
    ('Best Yunii fanart', ''),
    ('Artist of the year', ''),
    ('Most chaotic pestie', ''),
    ('Most biteable pestie', ''),
    ('The chaddest pestie', ''),
    ('Best gambler', ''),
    ('Worst gambler', ''),
    ('Best gamer', ''),
    ('Most wholesome pestie', ''),
    ('Most active discord pestie', ''),
    ('Most banned pestie', ''),
    ('Best minecraft builder', ''),
    ('Best cook', ''),
    ('Best clipper', ''),
    ('Best copypasta inventor', ''),
    ('Pestie of the Year', '');
